web:
  build: .
  command: python -u /opt/app/benchmark-postgresql-xml.py
  ports:
    - "5000:5000"
  #volumes:
  #  - .:/todo
  links:
    - db
db:
  image: postgres:9.6.3
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER:'foo'
    - POSTGRES_PASSWORD:'foobar'
    - POSTGRES_DB:'baz'
